//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.9
//
package co.koriel.yonapp;

import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.SharedPreferences;
import android.os.Build;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.design.widget.TabLayout;
import android.support.v4.app.FragmentManager;
import android.support.v4.content.ContextCompat;
import android.support.v4.content.LocalBroadcastManager;
import android.support.v4.view.ViewPager;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.preference.PreferenceManager;
import android.support.v7.widget.Toolbar;
import android.view.Menu;
import android.view.MenuItem;
import android.view.Window;
import android.view.WindowManager;
import android.widget.TextView;

import com.afollestad.materialdialogs.DialogAction;
import com.afollestad.materialdialogs.MaterialDialog;

import java.util.ArrayList;

import co.amazonaws.mobile.AWSMobileClient;
import co.koriel.yonapp.helper.InAppBillingHelper;
import co.koriel.yonapp.tab.TabPagerAdapter;
import co.koriel.yonapp.util.BackPressCloseHandler;

public class MainActivity extends AppCompatActivity {
    /** Bundle key for saving/restoring the toolbar title. */
    private final static String BUNDLE_KEY_TOOLBAR_TITLE = "title";

    /** The toolbar view control. */
    private Toolbar toolbar;

    private TabLayout tabLayout;
    private TabPagerAdapter tabPagerAdapter;
    private int tabPosition;

    /** The viewpager control */
    private ViewPager viewPager;

    private BackPressCloseHandler backPressCloseHandler;

    private MenuItem actionWrite;
    private MenuItem actionShare;
    private MenuItem actionCapture;
    private MenuItem actionSync;

    private InAppBillingHelper mHelper;

    /**
     * Initializes the Toolbar for use with the activity.
     */
    private void setupToolbar(final Bundle savedInstanceState) {
        toolbar = (Toolbar) findViewById(R.id.toolbar);
        // Set up the activity to use this toolbar. As a side effect this sets the Toolbar's title
        // to the activity's title.
        setSupportActionBar(toolbar);

        if (savedInstanceState != null) {
            // Some IDEs such as Android Studio complain about possible NPE without this check.
            assert getSupportActionBar() != null;
        }
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu_main, menu);

        actionWrite = menu.findItem(R.id.action_write);
        actionShare = menu.findItem(R.id.action_share);
        actionCapture = menu.findItem(R.id.action_capture);
        actionSync = menu.findItem(R.id.action_sync);

        actionWrite.setVisible(false);
        actionShare.setVisible(false);
        actionCapture.setVisible(false);
        actionSync.setVisible(false);
        return true;
    }

    @Override
    protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        backPressCloseHandler = new BackPressCloseHandler(this);

        if (Build.VERSION.SDK_INT >= 21) {
            Window window = getWindow();
            window.addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
            window.clearFlags(WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS);
            window.setStatusBarColor(ContextCompat.getColor(getApplicationContext(), R.color.status_bar_color));
        }

        // Obtain a reference to the mobile client. It is created in the Application class,
        // but in case a custom Application class is not used, we initialize it here if necessary.
        AWSMobileClient.initializeMobileClientIfNecessary(this);

        // Obtain a reference to the mobile client. It is created in the Application class.
        final AWSMobileClient awsMobileClient = AWSMobileClient.defaultMobileClient();

        setContentView(R.layout.activity_main);

        setupToolbar(savedInstanceState);

        getSupportActionBar().setDisplayShowTitleEnabled(false);

        // Initializing the TabLayout
        tabLayout = (TabLayout) findViewById(R.id.tabLayout);

        // Add tab into TabLayout
        tabLayout.addTab(tabLayout.newTab().setText(R.string.tab_home));
        tabLayout.addTab(tabLayout.newTab().setText(R.string.tab_notice));
        tabLayout.addTab(tabLayout.newTab().setText(R.string.tab_timetable));
        tabLayout.addTab(tabLayout.newTab().setText(R.string.tab_library));
        tabLayout.setTabGravity(TabLayout.GRAVITY_FILL);

        // Initializing ViewPager
        viewPager = (ViewPager) findViewById(R.id.viewPager);
        viewPager.setOffscreenPageLimit(4);

        // Creating TabPagerAdapter adapter
        tabPagerAdapter = new TabPagerAdapter(getSupportFragmentManager());

        // Set TabPagerAdapter on ViewPager
        viewPager.setAdapter(tabPagerAdapter);
        viewPager.addOnPageChangeListener(new TabLayout.TabLayoutOnPageChangeListener(tabLayout) {

            @Override
            public void onPageSelected(int position) {
                tabPosition = position;
                final TextView toolbarTitle = (TextView) findViewById(R.id.toolbarTitle);

                if (position == 0) {
                    try {
                        int count;
                        if ((count = tabPagerAdapter.getItem(0).getChildFragmentManager().getBackStackEntryCount()) > 0) {
                            FragmentManager.BackStackEntry backStackEntry = tabPagerAdapter.getItem(0).getChildFragmentManager().getBackStackEntryAt(count - 1);
                            String tag = backStackEntry.getName();

                            toolbarTitle.setText(tag);

                            if (tag.equals(getResources().getString(R.string.home_menu_oneline)) && count == 1) {
                                actionWrite.setVisible(true);
                            } else {
                                actionWrite.setVisible(false);
                            }
                        }
                        actionShare.setVisible(false);
                        actionCapture.setVisible(false);
                        actionSync.setVisible(false);
                    } catch (NullPointerException e) {
                        e.printStackTrace();
                    }
                } else if (position == 1) {
                    toolbarTitle.setText(R.string.app_name);
                    try {
                        actionWrite.setVisible(false);
                        actionCapture.setVisible(false);
                        actionSync.setVisible(false);
                        if (tabPagerAdapter.getItem(tabPosition).getChildFragmentManager().getBackStackEntryCount() == 0) {
                            actionShare.setVisible(false);
                        } else {
                            actionShare.setVisible(true);
                        }
                    } catch (NullPointerException e) {
                        e.printStackTrace();
                    }
                } else if (position == 2) {
                    try {
                        actionWrite.setVisible(false);
                        actionShare.setVisible(false);
                        actionCapture.setVisible(true);
                        actionSync.setVisible(true);
                    } catch (NullPointerException e) {
                        e.printStackTrace();
                    }
                } else {
                    try {
                        actionWrite.setVisible(false);
                        actionShare.setVisible(false);
                        actionCapture.setVisible(false);
                        actionSync.setVisible(false);
                    } catch (NullPointerException e) {
                        e.printStackTrace();
                    }
                }
            }
        });

        // Set TabSelectedListener
        tabLayout.setOnTabSelectedListener(new TabLayout.OnTabSelectedListener() {

            @Override
            public void onTabSelected(TabLayout.Tab tab) {
                viewPager.setCurrentItem(tab.getPosition());
                tabPosition = tab.getPosition();
                final TextView toolbarTitle = (TextView) findViewById(R.id.toolbarTitle);

                if (tabPosition == 0) {
                    try {
                        int count;
                        if ((count = tabPagerAdapter.getItem(0).getChildFragmentManager().getBackStackEntryCount()) > 0) {
                            FragmentManager.BackStackEntry backStackEntry = tabPagerAdapter.getItem(0).getChildFragmentManager().getBackStackEntryAt(count - 1);
                            String tag = backStackEntry.getName();

                            toolbarTitle.setText(tag);

                            if (tag.equals(getResources().getString(R.string.home_menu_oneline)) && count == 1) {
                                actionWrite.setVisible(true);
                            } else {
                                actionWrite.setVisible(false);
                            }
                        }

                        actionShare.setVisible(false);
                        actionCapture.setVisible(false);
                        actionSync.setVisible(false);
                    } catch (NullPointerException e) {
                        e.printStackTrace();
                    }
                } else if (tabPosition == 1) {
                    toolbarTitle.setText(R.string.app_name);
                    try {
                        actionWrite.setVisible(false);
                        actionCapture.setVisible(false);
                        actionSync.setVisible(false);
                        if (tabPagerAdapter.getItem(tabPosition).getChildFragmentManager().getBackStackEntryCount() == 0) {
                            actionShare.setVisible(false);
                        } else {
                            actionShare.setVisible(true);
                        }
                    } catch (NullPointerException e) {
                        e.printStackTrace();
                    }
                } else if (tabPosition == 2) {
                    toolbarTitle.setText(R.string.app_name);
                    try {
                        actionWrite.setVisible(false);
                        actionShare.setVisible(false);
                        actionCapture.setVisible(true);
                        actionSync.setVisible(true);
                    } catch (NullPointerException e) {
                        e.printStackTrace();
                    }
                } else {
                    toolbarTitle.setText(R.string.app_name);
                    try {
                        actionWrite.setVisible(false);
                        actionShare.setVisible(false);
                        actionCapture.setVisible(false);
                        actionSync.setVisible(false);
                    } catch (NullPointerException e) {
                        e.printStackTrace();
                    }
                }
            }

            @Override
            public void onTabUnselected(TabLayout.Tab tab) {

            }

            @Override
            public void onTabReselected(TabLayout.Tab tab) {
                viewPager.setCurrentItem(tab.getPosition());

                if (tabPagerAdapter.getItem(tabPosition).getChildFragmentManager().getBackStackEntryCount() > 0) {
                    onBackPressed();
                }
            }
        });
    }

    @Override
    protected void onResume() {
        super.onResume();

        if (!AWSMobileClient.defaultMobileClient().getIdentityManager().isUserSignedIn()) {
            // In the case that the activity is restarted by the OS after the application
            // is killed we must redirect to the splash activity to handle the sign-in flow.
            Intent intent = new Intent(this, SplashActivity.class);
            intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
            startActivity(intent);
            return;
        }

        final AWSMobileClient awsMobileClient = AWSMobileClient.defaultMobileClient();

        // pause/resume Mobile Analytics collection
        awsMobileClient.handleOnResume();

        // register notification receiver
        LocalBroadcastManager.getInstance(this).registerReceiver(notificationReceiver,
            new IntentFilter(PushListenerService.ACTION_SNS_NOTIFICATION));
    }

    @Override
    protected void onSaveInstanceState(final Bundle bundle) {
        super.onSaveInstanceState(bundle);
        // Save the title so it will be restored properly to match the view loaded when rotation
        // was changed or in case the activity was destroyed.
        if (toolbar != null) {
            bundle.putCharSequence(BUNDLE_KEY_TOOLBAR_TITLE, toolbar.getTitle());
        }
    }

    private final BroadcastReceiver notificationReceiver = new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            final ArrayList<String> arrayList = intent.getStringArrayListExtra(PushListenerService.INTENT_SNS_NOTIFICATION_DATA);
            String type = arrayList.get(0);

            SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());

            if (type.equals(PushListenerService.TYPE_ANNOUNCEMENT) && prefs.getBoolean("push_notice_all", true)) {
                new MaterialDialog.Builder(MainActivity.this)
                        .iconRes(R.drawable.ic_announcement_black_48dp)
                        .limitIconToDefaultSize()
                        .title(arrayList.get(1))
                        .content(arrayList.get(2))
                        .positiveText(R.string.dialog_ok)
                        .onPositive(new MaterialDialog.SingleButtonCallback() {
                            @Override
                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                dialog.dismiss();
                            }
                        })
                        .show();
            } else if (type.equals(PushListenerService.TYPE_ONELINE_NEW_COMMENT) && prefs.getBoolean("push_oneline_new_comment", true)) {
                new MaterialDialog.Builder(MainActivity.this)
                        .iconRes(R.drawable.ic_chat_black_48dp)
                        .limitIconToDefaultSize()
                        .title(arrayList.get(1))
                        .content(arrayList.get(2))
                        .positiveText(R.string.dialog_ok)
                        .onPositive(new MaterialDialog.SingleButtonCallback() {
                            @Override
                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                dialog.dismiss();

                                Intent restartIntent = getIntent();
                                restartIntent.putStringArrayListExtra("arrayList", arrayList);
                                finish();
                                startActivity(restartIntent);
                            }
                        })
                        .negativeText(R.string.dialog_cancel)
                        .onNegative(new MaterialDialog.SingleButtonCallback() {
                            @Override
                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                dialog.dismiss();
                            }
                        })
                        .show();
            } else if (type.equals(PushListenerService.TYPE_NEW_NOTICE) && prefs.getBoolean("push_yscec_new_notice", true)) {
                new MaterialDialog.Builder(MainActivity.this)
                        .iconRes(R.drawable.ic_fiber_new_black_48dp)
                        .limitIconToDefaultSize()
                        .title(arrayList.get(1))
                        .content(arrayList.get(2))
                        .positiveText(R.string.dialog_ok)
                        .onPositive(new MaterialDialog.SingleButtonCallback() {
                            @Override
                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                dialog.dismiss();
                                tabLayout.getTabAt(1).select();
                            }
                        })
                        .negativeText(R.string.dialog_cancel)
                        .onNegative(new MaterialDialog.SingleButtonCallback() {
                            @Override
                            public void onClick(@NonNull MaterialDialog dialog, @NonNull DialogAction which) {
                                dialog.dismiss();
                            }
                        })
                        .show();
            }
        }
    };

    @Override
    protected void onPause() {
        super.onPause();

        // Obtain a reference to the mobile client.
        final AWSMobileClient awsMobileClient = AWSMobileClient.defaultMobileClient();

        // pause/resume Mobile Analytics collection
        awsMobileClient.handleOnPause();

        // unregister notification receiver
        LocalBroadcastManager.getInstance(this).unregisterReceiver(notificationReceiver);
    }

    @Override
    public void onBackPressed() {

        int count;
        if ((count = tabPagerAdapter.getItem(tabPosition).getChildFragmentManager().getBackStackEntryCount()) > 0) {
            tabPagerAdapter.getItem(tabPosition).getChildFragmentManager().popBackStack();

            if (tabPosition == 1 && count == 2) {
                actionShare.setVisible(true);
            }
        } else {
            backPressCloseHandler.onBackPressed();
        }
    }
}
